# Konfiguracja komend społecznościowych
commands:
  dc:
    prefix: "&b&lDISCORD &8» &7Zapraszamy na naszego Discorda: "
    url: "https://discord.gg/aAtDAXufUH"
    hover: "&eKliknij, aby dołączyć do Discorda!"
  yt:
    prefix: "&c&lYOUTUBE &8» &7Sprawdź nasz kanał YouTube: "
    url: "https://youtube.com/@twojkanal"
    hover: "&eKliknij, aby otworzyć YouTube!"
