# Konfiguracja komend społecznościowych
commands:
  dc:
    message: "&b&lDISCORD &8» &7Zapraszamy na naszego Discorda: &ehttps://discord.gg/aAtDAXufUH"
  yt:
    message: "&c&lYOUTUBE &8» &7Sprawdź nasz kanał YouTube: &ehttps://youtube.com/@twojkanal"
